<?php

namespace ContainerGY1xv8M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNumberControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\NumberController' shared autowired service.
     *
     * @return \App\Controller\NumberController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/NumberController.php';

        $container->services['App\\Controller\\NumberController'] = $instance = new \App\Controller\NumberController(($container->privates['App\\Service\\NumberService'] ?? $container->load('getNumberServiceService')));

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\NumberController', $container));

        return $instance;
    }
}
