<?php

namespace ContainerGY1xv8M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRetrieveNumberCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\RetrieveNumberCommand' shared autowired service.
     *
     * @return \App\Command\RetrieveNumberCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/RetrieveNumberCommand.php';

        $container->privates['App\\Command\\RetrieveNumberCommand'] = $instance = new \App\Command\RetrieveNumberCommand(($container->privates['App\\Service\\NumberService'] ?? $container->load('getNumberServiceService')));

        $instance->setName('number:retrieve');

        return $instance;
    }
}
