<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGY1xv8M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGY1xv8M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGY1xv8M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGY1xv8M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGY1xv8M\App_KernelDevDebugContainer([
    'container.build_hash' => 'GY1xv8M',
    'container.build_id' => '5bbba076',
    'container.build_time' => 1667401095,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGY1xv8M');
