<?php

namespace ContainerKDWbR1q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenerateNumberCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\GenerateNumberCommand' shared autowired service.
     *
     * @return \App\Command\GenerateNumberCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/GenerateNumberCommand.php';

        $container->privates['App\\Command\\GenerateNumberCommand'] = $instance = new \App\Command\GenerateNumberCommand(($container->privates['App\\Service\\NumberService'] ?? $container->load('getNumberServiceService')));

        $instance->setName('number:generate');

        return $instance;
    }
}
