<?php

namespace ContainerKDWbR1q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNumberServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\NumberService' shared autowired service.
     *
     * @return \App\Service\NumberService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/NumberService.php';

        return $container->privates['App\\Service\\NumberService'] = new \App\Service\NumberService(($container->privates['App\\Repository\\NumberRepository'] ?? $container->load('getNumberRepositoryService')));
    }
}
