<?php

namespace ContainerKDWbR1q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWriteNumbersInFileCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\WriteNumbersInFileCommand' shared autowired service.
     *
     * @return \App\Command\WriteNumbersInFileCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/WriteNumbersInFileCommand.php';

        $container->privates['App\\Command\\WriteNumbersInFileCommand'] = $instance = new \App\Command\WriteNumbersInFileCommand(($container->privates['App\\Repository\\NumberRepository'] ?? $container->load('getNumberRepositoryService')));

        $instance->setName('number:writefile');

        return $instance;
    }
}
